on: [push] 
jobs: 
  build-engine-job:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@v12
      - uses: actions/checkout@v2
      - name: run emcc  
        working-directory: ./engine
        run: emcc -lembind -o engine.js engine.cpp
      - name: commit and push
        working-directory: ./engine
        run: |
          git config user.email "auto@auto.com"
          git config user.name autoauto
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add -A
          git commit -m "automated report"
          git push
        
