on:
  repository_dispatch:

jobs: 
  report-job:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@v12
      - uses: actions/checkout@v2
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
      - name: compile report
        working-directory: ./report
        run: g++ report.cpp -o report.x -std=c++20
      - name: run report
        working-directory: ./report
        run: |
          ./report.x
          bash sub_template.sh
      - name: run emcc  
        working-directory: ./html
        run: emcc report_page.cpp -o report.html --shell-file report_template.html -std=c++20 -sEXPORTED_FUNCTIONS="[]" 
      - name: commit and push
        working-directory: ./html
        run: |
          git config user.email "auto@auto.com"
          git config user.name autoauto
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add -A
          git commit -m "build report"
          git push
