on:
  push:
    paths:
      - engine/ml/train/todoactions.txt
jobs: 
  train-job:
    runs-on: ubuntu-latest
    steps:
      - name: toolchain
        run: |
          sudo add-apt-repository ppa:edd/misc
          sudo apt update
          sudo apt-get install mlpack=4.0.1-1.2204.1 libarmadillo-dev
      - name: compile  
        working-directory: engine/ml/train
        run: g++ train.cpp -o train.x -std=c++20
      - name: run train
        working-directory: engine/ml/train
        run: ./train.x
