on:
  push:
    paths:
      - engine/ml/train/todoactions.txt
jobs: 
  train-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
      - name: toolchain
        run: |
          sudo add-apt-repository ppa:edd/misc
          sudo apt-get update
          sudo apt-get install libmlpack-dev libarmadillo-dev
      - name: compile  
        working-directory: engine/ml/train
        run: g++ train.cpp -o train.x -std=c++20
      - name: run train
        working-directory: engine/ml/train
        run: ./train.x
